# Site settings
title: YouCanYouUp
email: mr.ke.shen@gmail.com
description: Blog site of Neo Shen
baseurl: /blog
encoding: utf-8
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: zy02636
github_username:  zy02636

# Build settings
markdown: kramdown
